import { createPullRequest } from '../../lib/github/prCreator';

async function runPrCreatorTest() {
  console.log("Starting PR Creator Replay Suite...\n");

  const mockGithubToken = process.env.GITHUB_ACCESS_TOKEN;
  if (!mockGithubToken) {
    console.error("❌ Test skipped: GITHUB_ACCESS_TOKEN is not set in environment.");
    process.exit(0);
  }

  // To run this test safely, explicitly set a repository you own.
  const testRepo = process.env.TEST_GITHUB_REPO;
  if (!testRepo) {
    console.error("❌ Test skipped: TEST_GITHUB_REPO is not set in environment.");
    process.exit(0);
  }

  const testDiff = `
diff --git a/test-file.txt b/test-file.txt
new file mode 100644
index 0000000..e69de29
--- /dev/null
+++ b/test-file.txt
@@ -0,0 +1 @@
+This is a test file added by the AutoSRE PR Creator.
`;

  try {
    console.log(`Attempting to create PR on ${testRepo}...`);
    const result = await createPullRequest({
      repoFullName: testRepo,
      incidentId: "test-123",
      patchDiff: testDiff,
      githubToken: mockGithubToken,
      prTitle: "test(autosre): Test PR Creator",
      prBody: "This is a test PR automatically generated by the Replay Suite.",
      baseBranch: "main",
    });
    
    if (result.success) {
      console.log("✅ PR created successfully!");
      console.log("PR URL:", result.prUrl);
      console.log("Branch:", result.branchName);
      console.log("Commit:", result.commitSha);
    } else {
      console.error("❌ Failed to create PR:", result.error);
      process.exit(1);
    }

  } catch (error) {
    console.error("\n❌ Replay Suite crashed:", error);
    process.exit(1);
  }
}

// Execute the suite
runPrCreatorTest();
