import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { prisma } from "@/lib/prisma";
import { createPullRequest } from "@/lib/github/prCreator";
import { evaluatePolicy } from "@/lib/safety/policyEngine";

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const session = await getServerSession(authOptions);
    if (!session || !session.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { patchArtifactId } = await req.json();
    if (!patchArtifactId) {
      return NextResponse.json({ error: "Missing patchArtifactId" }, { status: 400 });
    }

    // 1. Fetch Incident and Patch
    const incident = await prisma.incident.findUnique({
      where: { id },
      include: {
        repository: true,
        patches: {
          where: { id: patchArtifactId }
        }
      }
    });

    if (!incident || !incident.repository || incident.patches.length === 0) {
      return NextResponse.json({ error: "Incident, repository, or patch not found" }, { status: 404 });
    }

    const patch = incident.patches[0];

    if (patch.validationStatus !== "passed") {
      return NextResponse.json({ error: "Cannot create a PR for a patch that has not passed validation" }, { status: 400 });
    }

    // 2. Evaluate Policy for PR Creation
    const policyDecision = await evaluatePolicy({
      incidentId: incident.id,
      actionType: "pr_creation",
      confidenceScore: incident.confidence, // using incident confidence
      patchDiff: patch.patchDiff,
    });

    if (policyDecision.decision === "BLOCK_AND_ALERT") {
      return NextResponse.json({ error: `PR creation blocked by safety policy: ${policyDecision.reasonCodes.join(", ")}` }, { status: 403 });
    }

    const requiresApproval = policyDecision.decision === "REQUIRE_HUMAN_APPROVAL";

    // 3. Initialize IncidentAction
    const action = await prisma.incidentAction.create({
      data: {
        incidentId: incident.id,
        actionType: "open_pr",
        status: requiresApproval ? "pending_approval" : "pending",
        requiresApproval,
      }
    });

    if (requiresApproval) {
      return NextResponse.json({ 
        message: "Human approval required before opening PR.", 
        actionId: action.id,
        reason: policyDecision.reasonCodes.join(", ") 
      }, { status: 202 });
    }

    // 4. Fetch the authenticated user's linked GitHub token.
    // Do not fall back to a shared server token for this endpoint, to avoid
    // performing PR creation with the wrong account or elevated privileges.
    const userAccount = await prisma.account.findFirst({
      where: { user: { email: session.user.email as string }, provider: "github" }
    });
    const githubToken = userAccount?.access_token || "";

    if (!githubToken) {
      await prisma.incidentAction.update({
        where: { id: action.id },
        data: { status: "failed", failureReason: "No linked GitHub account token available." }
      });
      return NextResponse.json(
        { error: "No linked GitHub account token available. Please link your GitHub account." },
        { status: 401 }
      );
    }

    // 5. Format PR Body
    const prBody = `
## AutoSRE Remediation: ${incident.title}

This Pull Request was automatically generated by Recovera to remediate an active incident.

### Incident Details
- **Incident ID**: \`${incident.id}\`
- **Severity**: ${incident.severity}
- **Fingerprint**: \`${incident.fingerprint}\`

### Proposed Changes
${patch.changeSummary}

### Validation Status
- Static Analysis: **Passed**
- Blast Radius Policy: **Compliant**
- Risk Score: **${patch.riskScore}**

---
> 🤖 **Note:** Please review the changes carefully before merging. If you need to reject this fix, simply close this PR and Recovera will track the rejection.
`;

    // 6. Create PR
    const result = await createPullRequest({
      repoFullName: incident.repository.fullName,
      incidentId: incident.id,
      patchDiff: patch.patchDiff,
      githubToken,
      prTitle: `fix(autosre): ${incident.title}`,
      prBody,
      baseBranch: incident.repository.defaultBranch,
    });

    // 7. Update IncidentAction
    if (result.success) {
      await prisma.incidentAction.update({
        where: { id: action.id },
        data: {
          status: "opened",
          branchName: result.branchName,
          commitSha: result.commitSha,
          prUrl: result.prUrl,
        }
      });
      
      // Update Incident status explicitly to EXECUTED
      const { transitionIncidentState } = await import("@/lib/incidents/workflow");
      const { IncidentState } = await import("../../../../../../generated/prisma/client");
      await transitionIncidentState(
        incident.id, 
        IncidentState.EXECUTED,
        {
          actionType: "open_pr",
          details: `Opened PR ${result.prUrl}`
        }
      );

      return NextResponse.json({ success: true, prUrl: result.prUrl });
    } else {
      await prisma.incidentAction.update({
        where: { id: action.id },
        data: {
          status: "failed",
          failureReason: result.error,
        }
      });
      return NextResponse.json({ error: result.error }, { status: 500 });
    }

  } catch (error: any) {
    console.error("[Open PR API] Error:", error);
    return NextResponse.json({ error: "Internal Server Error", details: error.message }, { status: 500 });
  }
}
