import { NextRequest, NextResponse } from "next/server";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { prisma } from "@/lib/prisma";
import { createPullRequest } from "@/lib/github/prCreator";

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const session = await getServerSession(authOptions);
    if (!session || !session.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { patchArtifactId } = await req.json();
    if (!patchArtifactId) {
      return NextResponse.json({ error: "Missing patchArtifactId" }, { status: 400 });
    }

    // 1. Fetch Incident and Patch
    const incident = await prisma.incident.findUnique({
      where: { id },
      include: {
        repository: true,
        patches: {
          where: { id: patchArtifactId }
        }
      }
    });

    if (!incident || !incident.repository || incident.patches.length === 0) {
      return NextResponse.json({ error: "Incident, repository, or patch not found" }, { status: 404 });
    }

    const patch = incident.patches[0];

    if (patch.validationStatus !== "passed") {
      return NextResponse.json({ error: "Cannot create a PR for a patch that has not passed validation" }, { status: 400 });
    }

    // Initialize IncidentAction
    const action = await prisma.incidentAction.create({
      data: {
        incidentId: incident.id,
        actionType: "open_pr",
        status: "pending",
      }
    });

    // 2. Fetch user's GitHub Token (mocking for hackathon/MVP unless there's an active token stored)
    // In production, you'd fetch the user's Account linked to their Session for the access_token
    // For now, assume it's passed in headers or env if not found in db.
    let githubToken = process.env.GITHUB_ACCESS_TOKEN || "";
    
    // Attempt to get from DB
    const userAccount = await prisma.account.findFirst({
      where: { user: { email: session.user.email as string }, provider: "github" }
    });
    if (userAccount?.access_token) {
      githubToken = userAccount.access_token;
    }

    if (!githubToken) {
      await prisma.incidentAction.update({
        where: { id: action.id },
        data: { status: "failed", failureReason: "No GitHub token available." }
      });
      return NextResponse.json({ error: "No GitHub token available. Please link your GitHub account or set GITHUB_ACCESS_TOKEN." }, { status: 401 });
    }

    // 3. Format PR Body
    const prBody = `
## AutoSRE Remediation: ${incident.title}

This Pull Request was automatically generated by Recovera to remediate an active incident.

### Incident Details
- **Incident ID**: \`${incident.id}\`
- **Severity**: ${incident.severity}
- **Fingerprint**: \`${incident.fingerprint}\`

### Proposed Changes
${patch.changeSummary}

### Validation Status
- Static Analysis: **Passed**
- Blast Radius Policy: **Compliant**
- Risk Score: **${patch.riskScore}**

---
> 🤖 **Note:** Please review the changes carefully before merging. If you need to reject this fix, simply close this PR and Recovera will track the rejection.
`;

    // 4. Create PR
    const result = await createPullRequest({
      repoFullName: incident.repository.fullName,
      incidentId: incident.id,
      patchDiff: patch.patchDiff,
      githubToken,
      prTitle: `fix(autosre): ${incident.title}`,
      prBody,
      baseBranch: incident.repository.defaultBranch,
    });

    // 5. Update IncidentAction
    if (result.success) {
      await prisma.incidentAction.update({
        where: { id: action.id },
        data: {
          status: "opened",
          branchName: result.branchName,
          commitSha: result.commitSha,
          prUrl: result.prUrl,
        }
      });
      
      // Update Incident status
      await prisma.incident.update({
        where: { id: incident.id },
        data: { status: "in_review" }
      });

      return NextResponse.json({ success: true, prUrl: result.prUrl });
    } else {
      await prisma.incidentAction.update({
        where: { id: action.id },
        data: {
          status: "failed",
          failureReason: result.error,
        }
      });
      return NextResponse.json({ error: result.error }, { status: 500 });
    }

  } catch (error: any) {
    console.error("[Open PR API] Error:", error);
    return NextResponse.json({ error: "Internal Server Error", details: error.message }, { status: 500 });
  }
}
